"""STAR-evolved A-share picker (auto-generated by audit_picker.py).

Source node: edf78cfdfce8 gen=0  candidate=money_flow_clv_accum

Rationale:
Signal H (close-location-value money flow: where close sits inside today's H-L weighted by amount, rolled 5/10d) + signal A (volume tail) + signal G (recent gap-up that has digested) + light pullback structure. Premise: rising 10-day money flow with intraday closes hugging the high tells us informed buyers are absorbing supply faster than sellers can offer; combined with a digested gap and a non-spike last bar, the setup has 5-day continuation odds. Penalizes recent extreme single-day rips that exhaust demand. Best in stock-picking regimes with dispersion; weak in low-turnover dead markets.

Held-out metrics: mean_excess=+3.43pp, hit_rate=55%, sharpe~+7.72, DSR=+7.42
"""

import polars as pl

def pick(bars: pl.DataFrame) -> pl.DataFrame:
    df = bars.sort(["symbol", "ts"])

    # Close Location Value: where the close sits in the H-L range (-1..+1)
    df = df.with_columns([
        (((pl.col("close") - pl.col("low")) - (pl.col("high") - pl.col("close")))
         / (pl.col("high") - pl.col("low") + 1e-9)).alias("clv"),
    ])
    # Money flow = clv * amount (signed buying pressure)
    df = df.with_columns([
        (pl.col("clv") * pl.col("amount")).alias("mf_signed"),
        # Gap measure: today's open vs prior close
        ((pl.col("open") - pl.col("close").shift(1).over("symbol"))
         / (pl.col("close").shift(1).over("symbol").abs() + 1e-9)).alias("gap"),
    ])

    df = df.with_columns([
        pl.col("mf_signed").rolling_sum(window_size=5,  min_periods=3 ).over("symbol").alias("mf5"),
        pl.col("mf_signed").rolling_sum(window_size=10, min_periods=5 ).over("symbol").alias("mf10"),
        pl.col("mf_signed").rolling_sum(window_size=20, min_periods=10).over("symbol").alias("mf20"),
        pl.col("amount").rolling_sum(window_size=10, min_periods=5 ).over("symbol").alias("amt10_sum"),
        pl.col("amount").rolling_sum(window_size=20, min_periods=10).over("symbol").alias("amt20_sum"),
        pl.col("amount").rolling_mean(window_size=20, min_periods=10).over("symbol").alias("amt20"),
        pl.col("volume").rolling_mean(window_size=5,  min_periods=3 ).over("symbol").alias("vol5"),
        pl.col("volume").rolling_mean(window_size=20, min_periods=10).over("symbol").alias("vol20"),
        pl.col("close").rolling_mean(window_size=20, min_periods=10).over("symbol").alias("ma20"),
        pl.col("close").rolling_mean(window_size=60, min_periods=20).over("symbol").alias("ma60"),
        pl.col("gap").rolling_max(window_size=5, min_periods=1).over("symbol").alias("gap5_max"),
        (pl.col("close") / pl.col("close").shift(5 ).over("symbol") - 1.0).alias("ret5"),
        (pl.col("close") / pl.col("close").shift(20).over("symbol") - 1.0).alias("ret20"),
        (pl.col("close") / pl.col("close").shift(60).over("symbol") - 1.0).alias("ret60"),
        pl.col("pct_chg").rolling_max(window_size=3,  min_periods=1 ).over("symbol").alias("max3d"),
        pl.col("pct_chg").rolling_std(window_size=20, min_periods=10).over("symbol").alias("dvol20"),
        pl.col("high").rolling_max(window_size=20, min_periods=10).over("symbol").alias("hh20"),
        pl.col("low" ).rolling_min(window_size=20, min_periods=10).over("symbol").alias("ll20"),
        pl.col("clv").rolling_mean(window_size=5,  min_periods=3 ).over("symbol").alias("clv5"),
        pl.col("clv").rolling_mean(window_size=20, min_periods=10).over("symbol").alias("clv20"),
    ])

    last = df.group_by("symbol").tail(1)

    last = last.with_columns([
        # Money flow normalized
        (pl.col("mf10") / (pl.col("amt10_sum") + 1e-9)).alias("mf10_norm"),
        (pl.col("mf20") / (pl.col("amt20_sum") + 1e-9)).alias("mf20_norm"),
        # Money-flow acceleration: short minus longer
        ((pl.col("mf10") / (pl.col("amt10_sum") + 1e-9))
         - (pl.col("mf20") / (pl.col("amt20_sum") + 1e-9))).alias("mf_accel"),
        (pl.col("clv5") - pl.col("clv20")).alias("clv_accel"),
        (pl.col("vol5") / (pl.col("vol20") + 1e-9)).alias("vol_ratio"),
        ((pl.col("close") - pl.col("ma20")) / (pl.col("ma20").abs() + 1e-9)).alias("dist_ma20"),
        ((pl.col("ma20")  - pl.col("ma60")) / (pl.col("ma60").abs() + 1e-9)).alias("trend"),
        ((pl.col("close") - pl.col("ll20")) /
            (pl.col("hh20") - pl.col("ll20") + 1e-9)).alias("range_pos"),
    ])

    n = max(last.height, 1)

    last = last.with_columns([
        (pl.col("mf10_norm").fill_null(-1e9).rank() / n).alias("rk_mf10"),
        (pl.col("mf20_norm").fill_null(-1e9).rank() / n).alias("rk_mf20"),
        (pl.col("mf_accel" ).fill_null(-1e9).rank() / n).alias("rk_mf_accel"),
        (pl.col("clv5"     ).fill_null(-1e9).rank() / n).alias("rk_clv5"),
        (pl.col("clv20"    ).fill_null(-1e9).rank() / n).alias("rk_clv20"),
        (pl.col("clv_accel").fill_null(-1e9).rank() / n).alias("rk_clv_accel"),
        (pl.col("vol_ratio").fill_null(0.0).rank() / n).alias("rk_vol_ratio"),
        (pl.col("trend"    ).fill_null(-1e9).rank() / n).alias("rk_trend"),
        (1.0 - pl.col("max3d").fill_null(99.0).rank() / n).alias("rk_no_spike"),
        (1.0 - pl.col("dvol20").fill_null(99.0).rank() / n).alias("rk_low_vol"),
        # Reward digested gap: had a recent gap > 1.5% but ret5 is moderate (digested)
        ((pl.col("gap5_max") > 0.015).cast(pl.Float64)
            * (pl.col("ret5").fill_null(0.0).abs() < 0.05).cast(pl.Float64)
            ).alias("digested_gap"),
        # Above MA60 filter
        ((pl.col("close") > pl.col("ma60")).cast(pl.Float64)).alias("above_ma60"),
        # Distress filter
        ((pl.col("ret60") < -0.25).cast(pl.Float64)).alias("distress"),
        (pl.col("range_pos").fill_null(0.5)).alias("range_pos_fill"),
        pl.col("ret20").fill_null(0.0).alias("r20"),
    ])

    last = last.with_columns([
        (1.0 - (pl.col("range_pos_fill") - 0.60).abs() * 2.0).clip(0.0, 1.0).alias("range_pos_score"),
        (1.0 - (pl.col("r20") - 0.05).abs() * 3.0).clip(0.0, 1.0).alias("r20_score"),
    ])

    last = last.with_columns([
        (
              pl.col("rk_mf10")        * 0.14
            + pl.col("rk_mf20")        * 0.08
            + pl.col("rk_mf_accel")    * 0.10
            + pl.col("rk_clv5")        * 0.07
            + pl.col("rk_clv20")       * 0.05
            + pl.col("rk_clv_accel")   * 0.06
            + pl.col("rk_vol_ratio")   * 0.07
            + pl.col("rk_trend")       * 0.08
            + pl.col("rk_no_spike")    * 0.08
            + pl.col("rk_low_vol")     * 0.04
            + pl.col("digested_gap")   * 0.06
            + pl.col("above_ma60")     * 0.04
            + pl.col("range_pos_score")* 0.05
            + pl.col("r20_score")      * 0.04
            - pl.col("distress")       * 0.20
        ).fill_null(0.0).alias("score")
    ])

    return last.select(["symbol", "score"])